#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  in_fplug
#  ========
#  Copyright (C) 2015 Takeshi HASEGAWA
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

import sys, os, time, json
from pyfplug import *

duration = 30 # seconds
last_pool_time = {}

fplug_paths = sys.argv
del fplug_paths[0]

def collect(device_name):
    try:
        dev = FPlugDevice(device_name, debug = False, timeout = 20)
        r = [ time.time(), {
            'name': os.path.basename(device_name),
            'power': dev.get_power_realtime()
        } ]
        r[1]['power'] = 0 if r[1]['power'] is None else r[1]['power']
        print (json.dumps(r))
    except:
        pass

while True:
    t = time.time()
    polled_devices = 0
    for device_name in fplug_paths:
        pool = (last_pool_time[device_name] + duration < t ) if device_name in last_pool_time else True

        if pool:
            collect(device_name)
            last_pool_time[device_name] =  time.time()
            polled_devices += 1
    if polled_devices == 0:
        time.sleep(1)
#    else:
#        print("polled %d devices" % polled_devices, file)

